[features]
seeds = false
[programs.localnet]
charity_campaign = "CWZPtgNPbvoibF9GsYW9QMBAp6iHtcZydRLd7uWS3kQV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/artem/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
